"""dodana tablica dolasci

Revision ID: 32748741a613
Revises: deba0bee492c
Create Date: 2026-05-15 19:05:49.531408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32748741a613'
down_revision = 'deba0bee492c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dolasci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_vrijeme', sa.DateTime(), nullable=True),
    sa.Column('napomena', sa.String(length=200), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dolazak')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dolazak',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('datum_vrijeme', mysql.DATETIME(), nullable=True),
    sa.Column('napomena', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('clan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], name=op.f('dolazak_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('dolasci')
    # ### end Alembic commands ###
