"""dodana veza trener clan

Revision ID: aeb37a8bd315
Revises: 
Create Date: 2026-05-14 15:51:59.594665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb37a8bd315'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paketi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=False),
    sa.Column('cijena', sa.Integer(), nullable=True),
    sa.Column('trajanje_dana', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treneri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('specijalnost', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clanovi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=50), nullable=False),
    sa.Column('prezime', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('trener_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trener_id'], ['treneri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('paket_id', sa.Integer(), nullable=False),
    sa.Column('datum_uplate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.ForeignKeyConstraint(['paket_id'], ['paketi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uplate')
    op.drop_table('clanovi')
    op.drop_table('treneri')
    op.drop_table('paketi')
    # ### end Alembic commands ###
