"""dodana tablica dolasci

Revision ID: deba0bee492c
Revises: aeb37a8bd315
Create Date: 2026-05-15 18:56:13.357303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deba0bee492c'
down_revision = 'aeb37a8bd315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dolazak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_vrijeme', sa.DateTime(), nullable=True),
    sa.Column('napomena', sa.String(length=200), nullable=True),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clanovi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clanovi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uplata'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'paketi', ['paket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clanovi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_uplata'), 'paketi', ['paket_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    op.drop_table('dolazak')
    # ### end Alembic commands ###
